networks:
  proxy:
    external: true

services:
  app:
    image: esst/format-timesheet-reports:1.0.0-beta.1
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == format-cloud-1
      labels:
        - traefik.enable=true
        - traefik.http.routers.format-timesheet-reports.rule=Host(`tsr.format.lu`)
        - traefik.http.routers.format-timesheet-reports.entrypoints=websecure
        - traefik.http.routers.format-timesheet-reports.tls=true
        - traefik.http.routers.format-timesheet-reports.tls.certresolver=letsencrypt
        - traefik.http.routers.format-timesheet-reports.middlewares=secure-chain,gzip
        - traefik.http.services.format-timesheet-reports.loadbalancer.server.port=80
